platforms:
  cursor:
    type: cursor
    window_title: Cursor - Mushattention
    project_path: /Volumes/My Shared Files/Home/cheddar/mushattention/mushattention
    task_file_path: tasks.md
    additional_context_path: architecture.md
    initialization_delay_seconds: 5
    initialization:
    - keys: control+`
      delay_ms: 300
    - keys: command+l
      delay_ms: 300
    keystrokes:
    - keys: command+a
      delay_ms: 100
    - keys: backspace
      delay_ms: 100
    - keys: backspace
      delay_ms: 100
    - keys: command+l
      delay_ms: 300
    - keys: command+n
      delay_ms: 100
  windsurf_mushattention:
    type: windsurf
    window_title: WindSurf - Mushattention
    project_path: /Volumes/My Shared Files/Home/cheddar/mushattention/mushattention
    task_file_path: tasks.md
    additional_context_path: architecture.md
    initialization_delay_seconds: 8
    initialization:
    - keys: control+`
      delay_ms: 300
    - keys: control+kw
      delay_ms: 300
    - keys: command+l
      delay_ms: 300
    keystrokes:
    - keys: command+a
      delay_ms: 300
    - keys: backspace
      delay_ms: 100
    - keys: backspace
      delay_ms: 100
    - keys: command+l
      delay_ms: 300
    - keys: command+shift+l
      delay_ms: 100
  cursor_autopilot:
    type: cursor
    window_title: Cursor - Autopilot
    project_path: /Users/cheddarwhizzy/cheddar/cheddarwhizzy/cursor-autopilot
    task_file_path: tasks.md
    additional_context_path: architecture.md
    initialization_delay_seconds: 5
    initialization:
    - keys: control+`
      delay_ms: 300
    - keys: command+l
      delay_ms: 300
    keystrokes:
    - keys: command+a
      delay_ms: 100
    - keys: backspace
      delay_ms: 100
    - keys: backspace
      delay_ms: 100
    - keys: command+l
      delay_ms: 300
    - keys: command+n
      delay_ms: 100
  windsurf_meanscoop:
    type: windsurf
    window_title: meanscoop-payload
    project_path: /Users/cheddarwhizzy/cheddar/meanscoop-payload
    task_file_path: tasks.md
    additional_context_path: architecture.md
    initialization_delay_seconds: 12
    initialization:
    - keys: control+`
      delay_ms: 300
    - keys: control+kw
      delay_ms: 300
    - keys: command+l
      delay_ms: 300
    keystrokes:
    - keys: command+a
      delay_ms: 300
    - keys: backspace
      delay_ms: 100
    - keys: backspace
      delay_ms: 100
    - keys: command+l
      delay_ms: 300
    - keys: command+shift+l
      delay_ms: 100
general:
  active_platforms:
  - cursor
  - windsurf_mushattention
  staggered: true
  stagger_delay: 15
  initial_delay: 15
  send_message: true
  use_vision_api: false
  debug: true
  inactivity_delay: 240
  use_gitignore: true
slack:
  enabled: false
  bot_token: ''
  app_token: ''
  channels:
  - name: automation
    id: ''
  commands:
  - name: enable_auto
    description: Enable automatic mode
  - name: disable_auto
    description: Disable automatic mode
  - name: screenshot
    description: Take a screenshot of the IDE
  - name: set_timeout
    description: Set the timeout for continuation prompts
  - name: set_prompt
    description: Set the continuation or initial prompt
openai:
  vision:
    enabled: false
    api_key: ''
    model: gpt-4o
    max_tokens: 300
    temperature: 0.7
    conditions:
    - file_type: '*.py'
      action: save
      question: Does this code need any improvements?
    - file_type: '*.md'
      action: save
      question: Is this documentation clear and complete?
